### ISSUE TITLE
Items is [] when the component refreshes

### ISSUE THREAD

**Issue by phaistonian** [wellyshen/react-cool-virtual#146]
It seems that when you mount/unmount the component and the `itemCount` does not change the `items` is [] (after the first time).

A hacky way out of it is to do something like `itemCount: myCount + Math.round(Math.random() * 100)` and filter later.

In other words, some kind of check takes place based on the `itemCount` that causes cache-related (I presume) issues.

**Comment by wellyshen** [comment]
@phaistonian Thank you, I will investigate it soon.

**Comment by wellyshen** [comment]
@phaistonian Can you give me a minimal reproduced code or [CodeSandbox](https://codesandbox.io) for this issue?

**Comment by phaistonian** [comment]
it's 11pm down here as well (Greece).

Will see to it tomorrow.

Thank you.

**Comment by phaistonian** [comment]
Here's a video that will probably indicate the issue.

It seems this is state-related.

https://user-images.githubusercontent.com/796530/122469768-ff14eb00-cfc5-11eb-841f-0d6a529cd0af.mp4

**Comment by wellyshen** [comment]
@phaistonian I tried to reproduce your case but I can't make it. Did I miss something? Here's the [CodeSandbox](https://codesandbox.io/s/practical-stallman-kilji).

https://user-images.githubusercontent.com/21308003/122514174-1b546e80-d03e-11eb-9e88-2daecae6770a.mov

**Comment by phaistonian** [comment]
Indeed, it does work in this - super similar scenario.

I am not sure what the issue is, to be honest.

If you want we can have a zoom call  (or have a quick chat) to illustrate the issue — I am afraid I can't share the repo publicly.

**Comment by wellyshen** [comment]
@phaistonian Would you mind to simulate your scenario with a CodeSandbox for me?

**Comment by phaistonian** [comment]
I will need some time and these days are hectic, plus, this scenario is pretty much identical to what you did.

Does the following help at all?
![CleanShot 2021-06-18 at 09 18 38@2x](https://user-images.githubusercontent.com/796530/122515522-3ca16480-d016-11eb-9b34-93ea69242745.png)

**Comment by wellyshen** [comment]
@phaistonian Can you check the `itemsFiltered.length` when there's no filter applied. This hook returns empty `items` when the `itemCount` option is falsy.

**Comment by phaistonian** [comment]
That's not the issue :(

https://user-images.githubusercontent.com/796530/122516823-e9c8ac80-d017-11eb-9c2c-5b65926b9d8f.mp4

**Comment by wellyshen** [comment]
@phaistonian Got it, I think we need a reproduced environment for debugging, plz take your time to prepare it for me. I will think about this case at the same time.

**Comment by phaistonian** [comment]
I can give you access to my system (with AnyDesk or something) to take a look.

That would speed things up.

Wanna go that way?

**Comment by wellyshen** [comment]
@phaistonian Yes you can invite me, but I might check it now maybe later. I think I know your case just not quite sure. If you wrap this hook with render items into a component, I think it might solve your issue.

**Comment by phaistonian** [comment]
I _sense_ this will solve this too — but this a hack.

**Comment by wellyshen** [comment]
@phaistonian How about put the items length as a state?

**Comment by phaistonian** [comment]
Tried it.

That's not it either.

**Comment by wellyshen** [comment]
@phaistonian Plz invite me, I will take time to investigate it.

**Comment by phaistonian** [comment]
Let's try whereby https://whereby.com/thebestco

**Comment by wellyshen** [comment]
@phaistonian Plz give me the permission to check the code. It will be helpful.

**Comment by wellyshen** [comment]
> Let's try whereby https://whereby.com/thebestco

It's like a video chat mate. Do you think we should have a reproduced CodeSandbox here? It can help others as well.

**Comment by phaistonian** [comment]
@wellyshen  Will try to make some time to do it later.

**Comment by wellyshen** [comment]
@phaistonian Okay, I will check once you provide it.

**Comment by phaistonian** [comment]
So, here's how I _fixed_ it.

- Changing the `itemCount` in any way, fixes this issue.
- Used a pseudo flag (`isLoading`) to switch from zero to the actual count.
- I still think this is sort of buggy - perhaps some `useEffect` or `useLayoutEffect` is acting up

I will try and get a better look later.

![CleanShot 2021-06-18 at 13 31 26@2x](https://user-images.githubusercontent.com/796530/122548036-85b6e000-d039-11eb-91b9-960999714075.png)

**Comment by wellyshen** [comment]
@phaistonian Yes, this hook use `useLayoutEffect` for handling the `itemCount`. However `useLayoutEffect` is called before  `useEffect`. Can you help to double-check it?

**Comment by phaistonian** [comment]
Yes - I did confirm it.

If the itemCount remains the same, it's as if it's treated as zero.

Will try and bundle your code to a js file to see where exactly the issue is (bundle from .ts to js).

**Comment by wellyshen** [comment]
@phaistonian I need your reproduced case, if you can provide it via CodeSandbox, it will be super helpful.

**Comment by phaistonian** [comment]
Got it.

![CleanShot 2021-06-18 at 15 26 50@2x](https://user-images.githubusercontent.com/796530/122560732-a38c4100-d049-11eb-8d09-48583ba5d669.png)

The dependencies to the effect do not change and so this effect is not invoked and so the `handleScroll` method (nested in the event) is also not called.

My guess is that you need to introduce another dependency that will be reset on unmount (`useEffect`).

**Comment by phaistonian** [comment]
![CleanShot 2021-06-18 at 15 42 52@2x](https://user-images.githubusercontent.com/796530/122562605-ed762680-d04b-11eb-9c9c-8793d8bf92c6.png)

**Comment by wellyshen** [comment]
@phaistonian We can't pass the refs to the dependencies they will always trigger the effect function. What I want to know is under what kind of scenario that the effect function won't be triggered, that's why I need your help for the reproduced code through CodeSandbox, once I have the reproduced environment, I can solve this problem.

**Comment by phaistonian** [comment]
I really can't get it on Codesandbox - it's part of our work repo. Plus decoupling it will take tons of time :(

I might be able to try it on the weekend, can't promise it tho.

**Comment by wellyshen** [comment]
@phaistonian Okay, no problem. All I need is the reproduce circumstance not your business code lol.

**Comment by wellyshen** [comment]
@phaistonian The `items` only update when the `itemCount` changed, and this also how [React.useEffect](https://reactjs.org/docs/hooks-reference.html#conditionally-firing-an-effect) works. So the same `itemCount` won't trigger the updating of `items`. But what I don't understand is why your get the empty list?

**Comment by wellyshen** [comment]
@phaistonian You can try the latest version of this package to see if this issue still exists or not. If it still exists, leave a reproduce code via CodeSandbox, I will fix it soon.

**Comment by phaistonian** [comment]
@wellyshen  will do :-) Thanks

**Comment by crow7m** [comment]
> @phaistonian You can try the latest version of this package to see if this issue still exists or not. If it still exists, leave a reproduce code via CodeSandbox, I will fix it soon.

Hi, thank you for the great library. was the issue with itemCount fixed  ? thank you

**Comment by wellyshen** [comment]
@crow7m Have you encountered the issue?

**Comment by wellyshen** [comment]
Close due to inactive, plz use the latest version to see whether this issue still occurs or not.

**Comment by abearief1405** [comment]
Hai @wellyshen first things first I want to thankfull for the library.

I Had similiar issue with this. After successfull render the components, I move to other pages and back to the components,  data wont to render it's because `isItemLoadedArr[loadIndex] = true`.

So I used to `const [isItemLoadedArr, setIItemLoadedArr] = useState([]);`
create useEffect 
```
useEffect(() => {
    if (isItemLoadedArr.length > 0) {
        const resetIsLoaderArr = isItemLoadedArr.map((dt) => false)
        setIItemLoadedArr(resetIsLoaderArr)
    }

}, []) 
```
pass `isItemLoadedArr` to `loadMore: (e) => loadData(e, setActivities, isItemLoadedArr)`
and the last things pass `isItemLoadedArr` to `const loadData = async ({ loadIndex }, setActivities, isItemLoadedArr) => {...};`

This also avoid the callback from being invoked repeatedly.


This is my full code:

```
import React, { useEffect, useState } from "react";
import useVirtual from "react-cool-virtual";
import axios from "axios";

const api = {
    xxx
}

const loadData = async ({ loadIndex }, setActivities, isItemLoadedArr) => {
    isItemLoadedArr[loadIndex] = true;

    try {
        const { data: activities } = await axios.get(`${api}/${loadIndex + 1}`);

        if (activities.data !== null) {
            setActivities((prevActivities) => {
                const nextActivities = [...prevActivities];

                activities.data.forEach((comment) => {
                    nextActivities[comment.id - 1] = comment;
                });

                return nextActivities;
            });
        } else {
            isItemLoadedArr[loadIndex] = false;
        }
    } catch (err) {
        isItemLoadedArr[loadIndex] = false;
        loadData({ loadIndex }, setActivities, isItemLoadedArr);
    }
};

const DataActivities = ({ total }) => {
    const cActivities = total;
    const batchActivities = 5;

    const [isItemLoadedArr, setIItemLoadedArr] = useState([]);
    const [activities, setActivities] = useState([]);
    const { outerRef, innerRef, items } = useVirtual({
        itemCount: cActivities,
        itemSize: 400,
        loadMoreCount: batchActivities,
        isItemLoaded: (loadIndex) => isItemLoadedArr[loadIndex],
        loadMore: (e) => loadData(e, setActivities, isItemLoadedArr)
    });

    useEffect(() => {
        if (isItemLoadedArr.length > 0) {
            const resetIsLoaderArr = isItemLoadedArr.map((dt) => false)
            setIItemLoadedArr(resetIsLoaderArr)
        }

    }, [])

    return (
        <div
            className="outer"
            style={{ width: "300px", height: "500px", overflow: "auto" }}
            ref={outerRef}
        >
            <div ref={innerRef}>
                {items.map(({ index, measureRef }) => (
                    <div
                        key={activities[index]?.id || `fb-${index}`}
                        className={`item ${index % 2 ? "dark" : ""}`}
                        style={{ padding: "16px", minHeight: "122px" }}
                        ref={measureRef} // Used to measure the unknown item size
                    >
                        {activities[index]
                            ? `${activities[index].id}. ${JSON.stringify(activities[index])}`
                            : "⏳ Loading..."}
                    </div>
                ))}
            </div>
        </div>
    );
};

export default DataActivities;
```

Hope it's help, thank you.
