### ISSUE TITLE
New option: scrollToTopOnChange

### ISSUE THREAD

**Issue by phaistonian** [wellyshen/react-cool-virtual#147]
The title explains it :)

When the `itemCount` changes, i.e. when new items are passed, the optionally (or by default) `scrollTo(0)` should be invoked.

Ps: what I do now is a `useEffect`.

**Comment by wellyshen** [comment]
@phaistonian Great idea but the **reset to top** can't be a default option, because of the case of [lazily loading](https://github.com/wellyshen/react-cool-virtual#working-with-a-loading-indicator) will be influenced. Can you share your use case with me? I need more information for the feature.

**Comment by phaistonian** [comment]
Say you are filtering a list of items based in user input and you have scrolled down to the previous list. 

Since the list updates you should have the scroll position move to too.

**Comment by wellyshen** [comment]
@phaistonian Okay, it makes sense. Will add this feature soon.

**Comment by wellyshen** [comment]
@phaistonian Thank you for this idea. This feature will be released tonight.
