### ISSUE TITLE
Flicker in blitzjs project (with React v18)

### ISSUE THREAD

**Issue by Visualizeit** [wellyshen/react-cool-virtual#170]
# Bug Report

## Describe the Bug

In the blitzjs project, the list items appear to flicker when scrolling

## How to Reproduce
Go to codesandbox and scroll down the list

## CodeSandbox Link

https://codesandbox.io/s/romantic-bhabha-3d6wv?file=/app/pages/index.tsx

## Screenshots

https://user-images.githubusercontent.com/61679509/124274890-67da9680-db74-11eb-8c43-3f677608a6dc.mp4

## Your Environment

- Device: pc
- OS: Windows
- Browser: Chrome
- Version: 91.0

## Additional Information

This bug only appears in blitzjs and works normally on nextjs

**Comment by wellyshen** [comment]
@Visualizeit Thank you for reporting this issue, will take time to investigate it.

**Comment by wellyshen** [comment]
@Visualizeit This issue comes from React v18. However, v18 is not stable yet.  I'd recommend you to use the latest [stable version](https://reactjs.org/versions) of React for now. I will re-check this issue when React v18 is officially released.

**Comment by Visualizeit** [comment]
@wellyshen okay, thank you
