### ISSUE TITLE
scrollToItem not resolving with dynamic height items

### ISSUE THREAD

**Issue by subblue** [wellyshen/react-cool-virtual#176]
# Bug Report

Before I get to the bug details I would first like to say how impressed I've been with using this library so far. 
It is straight-forward, well documented and I really like how the implementation doesn't make assumptions on the way to use your components. 
Thanks for the time and effort you have put into this! 💯 

## Describe the Bug

I have a content panel with a long list of variable height items, each using the `measureRef` option.
The `scrollToItem` action with the `smooth` option can get caught in an unbreakable bouncing animation loop as it constantly tries to find the target scroll offset position - see the glitchy video examples below.

## How to Reproduce
In my case the content items are quite large so it happens more easily if the initial `itemSize` is set to a small value like `100`, and less so if it is something like `window.innerHeight`. It also seems to happen less often with `align: 'start'` but can still occur.

Also note that the measured heights of the items are sometimes floating point values (I'm using an HDPI display).

Forcing the measured size to be rounded down to an integer:
```ts
const measuredSize = Math.floor(target.getBoundingClientRect()[sizeKey]);
```
at
https://github.com/wellyshen/react-cool-virtual/blob/0259cf17b9badf13a5275230d491e218979e40d2/src/useVirtual.ts#L351

helped, but the problem still happens occasionally.

## CodeSandbox Link

I managed to replicate the problem here (it might take a few clicks of the button to see the issue):
https://codesandbox.io/s/rcv-scroll-to-methods-forked-62gf3?file=/index.js

## Expected Behavior

It scrolls to position without getting stuck in a bouncing around animation.

It might be that dynamic height items will always have potential for indeterministic behaviour so maybe there needs to be an extra guard against getting stuck in a never ending animation (maybe if the direction changes more than a couple of times it will end the animation).

## Screenshots

The issue when it appears on CodeSandbox:
https://user-images.githubusercontent.com/3010/124582941-6c3fd180-de4a-11eb-8ed0-dc7496366ca2.mp4

The extreme case from my app (flicker warning!):
https://user-images.githubusercontent.com/3010/124571677-ecad0500-de3f-11eb-8dec-c1e54848846e.mp4

## Your Environment

- Device: Mac Pro
- OS: MacOS 11.4
- Browser: Chrome
- Version: v92.0.4515.80

**Comment by wellyshen** [comment]
@subblue Thank you for reporting this issue, your information really helpful, will fix it soon.

**Comment by wellyshen** [comment]
@subblue This issue will be fixed alongside the next release, stay tune!
