### ISSUE TITLE
How to do Full Screen Infinite loader that is driven by the main browser vertical scroll bar?

### ISSUE THREAD

**Issue by karanmartian** [wellyshen/react-cool-virtual#195]
Hey,
This is a super cool hook. But the examples that are given are only of scrolling inside some kind of a fixed window frame with outer and inner refs.

I am trying to load more items when the user scrolls down using the main vertical scrollbar of the browser window. This is very critical to my Newsfeed application. How can this be done? Can you provide an example?

**Comment by wellyshen** [comment]
@karanmartian Thank you for giving it a try. What you mentioned is called _window scroll_. However, this hook doesn't support that yet. That will be implemented in the near future, stay tuned. Please refer to #144.

**Comment by karanmartian** [comment]
@wellyshen this is a really important feature. How long will it take to enable this feature? Can you provide any directions to change the source code of this hook to enable this?

**Comment by wellyshen** [comment]
@karanmartian It takes time to implement. If you are eager to use that, you can use [react-virtualized](https://github.com/bvaughn/react-virtualized) atm.
