### ISSUE TITLE
Feature Request: support window scrolling + scroll restoration.

### ISSUE THREAD

**Issue by meotimdihia** [wellyshen/react-cool-virtual#220]
# Feature Request

This lib looks totally promising. I want to use this library on my website. 
But it missed the 2 most important features: window scrolling + scroll restoration when navigating back.  
I tried https://virtuoso.dev/ but it doesn't work with scroll restoration.  

Other libraries are hard to use and buggy. I spent 2-3 days learn react-window + virtuoso, and disappointed 😥
Also, I hope you can test with next.js - the most popular react framework.

**Comment by meotimdihia** [comment]
> @meotimdihia For the scrolling restoration, can you achieve that via the [scroll-to methods](https://github.com/wellyshen/react-cool-virtual#scroll-to-offset--items)?

Thanks for the answer. Virtuoso is supported this too. I don't know why but it doesn't work in my next.js app.

And I don't test react-cool-virtual yet. The package doesn't support windows scroll currently.

**Comment by wellyshen** [comment]
@meotimdihia Got it. The logic of window scrolling is much different from container scrolling. I'm still thinking about the architecture for that, it might not be supported atm.

**Comment by wellyshen** [comment]
Close due to #144
