### ISSUE TITLE
App crashes when scrolling with drag bar

### ISSUE THREAD

**Issue by fourteenmeister** [wellyshen/react-cool-virtual#224]
In **[this example](https://codesandbox.io/s/rcv-dynamic-size-0wurg?fontsize=14&hidenavigation=1&theme=dark)** when you try to scroll with the mouse, the page freezes and crashes.

Maybe this is mine alone?

**Comment by wellyshen** [comment]
@fourteenmeister Does it occur on the CodeSandbox?

**Comment by fourteenmeister** [comment]
CodeSandbox

**Comment by fourteenmeister** [comment]
> @fourteenmeister Это происходит в CodeSandbox или в вашей среде разработки?

CodeSandbox

**Comment by wellyshen** [comment]
@fourteenmeister Can you tell me your environment and package versions that you are using on the CodeSandbox?

**Comment by fourteenmeister** [comment]
so in this example everything is indicated
![image](https://user-images.githubusercontent.com/3837141/129344367-9cc07088-b83c-41fe-898d-e733945080f0.png)

**Comment by fourteenmeister** [comment]
recorded a demo

![Peek 2021-08-13 13-52](https://user-images.githubusercontent.com/3837141/129346663-29d2cb3e-8ce8-4e07-a947-fcff3efc8462.gif)

**Comment by wellyshen** [comment]
@fourteenmeister What browser that you are using?

**Comment by fourteenmeister** [comment]
chrome  92.0.4515.131

**Comment by wellyshen** [comment]
@fourteenmeister Thank you, I can reproduce it, will fix it soon. For now, you can enlarge the [itemSize](https://github.com/wellyshen/react-cool-virtual#itemsize) to avoid this issue.

**Comment by wellyshen** [comment]
@fourteenmeister This issue should be fixed in [v0.4.6](https://github.com/wellyshen/react-cool-virtual/releases/tag/v0.4.6), thanks.

**Comment by fourteenmeister** [comment]
> @fourteenmeister This issue should be fixed in [v0.4.6](https://github.com/wellyshen/react-cool-virtual/releases/tag/v0.4.6), thanks.

Excellent! Thanks for the quick fix
