### ISSUE TITLE
TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by dehmer** [wellyshen/react-cool-virtual#244]
# Bug Report

## Describe the Bug

Abstract list components receives rows as props. useVirtual() is used in this component.
Filtering (i.e. truncating) rows in parent component leads to `TypeError: Cannot read property 'start' of undefined`,
but only if original/longer list was scrolled down a page or so before filtering.

## How to Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

### Usage

The error show a little less frequent, when `entries` are managed as local state (commented out below).
`resetScroll` seems to have no impact on error condition.

```
  const entries = props.entries
  // const [entries, setEntries] = React.useState(props.entries)
  // React.useEffect(() => {
  //   setEntries(props.entries)
  // }, [props.entries])

  const { outerRef, innerRef, items, scrollToItem } = useVirtual({
    itemCount: entries.length,
    resetScroll: true
  })

```

### Steps to reproduce in CodeSandbox (provided below):

1. Display 800 list rows
2. Scroll down a page or more
3. Shorten list to 2 rows (combo box)
4.`TypeError: Cannot read property 'start' of undefined` @ `var currStart = msData[vStop].start;`

In case entries are managed as state in <List/>
4. Repeat steps 1, 2 and 3
5. TypeError: `Cannot read property 'start' of undefined` @ var currStart = msData[vStop].start; 

The primary problems seems to be that `items` array is often 'overshooting', i.e. not in sync with rows/entries, `items` length exceeds `rows` length. In this case I can only return `null` as a result:

```
  const card = ({ index, measureRef }) => {
  
    // Why can this happen?
    if (index >= entries.length) {
      console.warn('<List/> overshooting', `${index}/${entries.length}`)
      return null
    }

    const entry = entries[index]
    return child({
      entry,
      id: entry.id,
      focused: focusId === entry.id,
      selected: selected.includes(entry.id),
      ref: measureRef
    })
  }

```

## CodeSandbox Link

https://codesandbox.io/s/keen-thunder-e0f5m

## Expected Behavior

Don't crash and burn, when list is filtered in parent.

## Your Environment

* MacBook Pro (15-inch, 2017)
* macOS 11.5.2 (Big Sur)
* Electron 13.1.6

```
process.versions = {
  "node": "14.16.0",
  "v8": "9.1.269.36-electron.0",
  "uv": "1.40.0",
  "zlib": "1.2.11",
  "brotli": "1.0.9",
  "ares": "1.16.1",
  "modules": "89",
  "nghttp2": "1.41.0",
  "napi": "7",
  "llhttp": "2.1.3",
  "openssl": "1.1.1",
  "icu": "68.1",
  "unicode": "13.0",
  "electron": "13.1.6",
  "chrome": "91.0.4472.124"
}

```
## Additional Information

Scrolling down the 800 row list from CodeSandbox in Safari frequently show the following error message in console (without stack trace): `[Error] ResizeObserver loop completed with undelivered notifications. (x17)`
But Safari is NOT the target environment! Might be helpful anyway.

**Comment by dehmer** [comment]
Because I wanted to create an animated GIF from screen for a long time.
Besides that, it only shows that if empty list is unmounted between long and short list, the error naturally does not occur.
Probably not very helpful...

```
 React.useEffect(() => {
    return () => console.log('<List/> unmounting...')
  }, [])

  // don't render list without item:
  const list = items.length
    ? items.map(card)
    : null
```  

![issue#244](https://user-images.githubusercontent.com/322462/132117573-f924527f-2679-43ab-aeb6-dadfe9747eeb.gif)

**Comment by wellyshen** [comment]
@dehmer Thank you, the fixing will be released in [v0.5.1](https://github.com/wellyshen/react-cool-virtual/releases/tag/v0.5.1)

**Comment by dehmer** [comment]
Thanks! I will give it a spin and report back.

**Comment by wellyshen** [comment]
@dehmer It has be released, thanks mate.

**Comment by dehmer** [comment]
@wellyshen 👍 Looks pretty damn good! 
And thanks for the quick fix!

Two question though
A. Can you confirm that 'overshooting' still happens and returning `null` in this case is advised?
B. Taking list model from props (entries, rows or whatever) is OK, no need for local `useState(props.row)`?

**Comment by wellyshen** [comment]
@dehmer 

- For A. I don't need the logic of `overshooting` when I was reproducing this issue locally.
- For B. We don't need the local state.

**Comment by dehmer** [comment]
Hmm, OK thanks. I will have a closer look regarding overshooting.

**Comment by dehmer** [comment]
@wellyshen Exception is gone, but overshooting still happens in my updated CodeSandbox: https://codesandbox.io/s/keen-thunder-e0f5m

**Comment by wellyshen** [comment]
@dehmer It's because the `rows` prop is updated before the item's `index`. That's the race condition of the state between the app component and the hook. You can keep the error handling or maintain the full rows data for index reference.

**Comment by dehmer** [comment]
@wellyshen Got it! 
I leave it as is for now. The list model is managed two levels up in the component hierarchy and I'm reluctant to pull useVirtual() so far up.
Many thanks for your help! ❤️
