### ISSUE TITLE
Wrong indices passed to loadMore

### ISSUE THREAD

**Issue by blutorange** [wellyshen/react-cool-virtual#284]
# Bug Report

First of all, this library is great and really easy to use. I was making a demo with lazy loading + filtering and I think I found a bug:

## Describe the Bug

The indices passed to `loadMore` are not always correct. For example:

* 50 items, page size 5 
* Scroll down to the very bottom
* Now, the `loadMore` method receives `e.startIndex=50` and `e.stopIndex=54`.

This is wrong because there are only 50 items. When the user scrolls down quickly to the bottom, the `loadMore` method is never called with indices `45-49`. Then the items are never  loaded and the user keeps seeing the loading animation.

Also, even if you don't scroll to the end of the list, scrolling to certain positions results in the data not being loaded.

## CodeSandbox Link

https://codesandbox.io/s/rcv-infinite-scroll-forked-g48o7

This is pretty much just the Infinite Scroll demo (https://github.com/wellyshen/react-cool-virtual#infinite-scroll). That demo itself contains a bug when loading the data -- it just appends the new comments to the existing array, but when the user scroll quickly the indices are not necessarily continuous. I fixed this in the demo by setting the item to the appropriate index.

Other than that, I only added a console log to `loadMore`.

This is a screenshot of what can happen when quickly scrolling down to the last item. `loadMore` should load items `500-504`, which don't even exist. Note that the last call to `loadMore` was with the indices `430-434`. This results in the visible items not getting loaded at all and the user keeps seeing the loading animation.

![image](https://user-images.githubusercontent.com/2456413/137028501-8a3f08c4-c4c8-4a92-9a47-1db3eb8776cc.png)

## Expected Behavior

The correct indices for the visible range are passed to `loadMore` and `isItemLoaded`.

I've seen that the index is computed as `Math.floor((vStop + 1) / loadMoreCount)` (https://github.com/wellyshen/react-cool-virtual/blob/master/src/useVirtual.ts#L445). With `+1` it may skip to the next page / batch. It also does not take into account the `vStart` value, when the user scrolls down quickly those items may not be loaded either.

I'm not quite sure, but I suppose the computation should use the `vStart` and `vStop` values, quantize those to the corresponding page / batch number, then use that and take care of the case when two pages / batches are visible on the screen and need to be loaded?

**Comment by wellyshen** [comment]
@blutorange Thank you for giving this package a try, let me explain these issues as follows:
- For the event properties of the `loadMore`: The properties are used for indicating the next loading items if you want to get the current displaying items, please use  [onScroll](https://github.com/wellyshen/react-cool-virtual#onscroll) instead.
- For the quickly scrolling: When the user scrolls forward quickly some of the loading items are skipped, that's a limitation. However, when the user scrolls backward, the skipped items should be re-fetched. I have fixed this issue through this [PR](https://github.com/wellyshen/react-cool-virtual/pull/285).
- For the infinite example: Yes, there's a bug. I have updated the example by following your solutioln.
