### ISSUE TITLE
How to use react-cool-virtual with grid css ?

### ISSUE THREAD

**Issue by ptimer** [wellyshen/react-cool-virtual#323]
I have responsive grid layout with posts that have titles, cover images, descriptions etc. 
React-cool-virtual doesn't detect position of my elements. It's behaviour like it has deal with list and set start position of elements like 0 - 200 - 400 - 600 px etc. Maybe you have some examples i've not found or ideas about such type of problem ? 
P.S start property can't be changed. How then to implement margins in grid ?

**Comment by wellyshen** [comment]
@ptimer This library is designed for using a one-dimension way. You can turn your styles into that way.
