### ISSUE TITLE
How to test app with react-cool-virtual ? 

### ISSUE THREAD

**Issue by ptimer** [wellyshen/react-cool-virtual#324]
I have an errors react-testing-library doesn't see content because it has not rendered yet. How to test such app ?

**Comment by wellyshen** [comment]
@ptimer This library uses [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) under the hook, you need to [mock it](https://github.com/wellyshen/react-cool-virtual/blob/master/src/__tests__/useVirtual.tsx#L131) in your testing environment.
