### ISSUE TITLE
Bi-directional infinite scroll example

### ISSUE THREAD

**Issue by pleerock** [wellyshen/react-cool-virtual#359]
Would be really helpful to have an example of infinite scroll working in both sides (up and down). I was only able to find examples to top or bottom, but not both. Use cases: chat applications.

Thank you for your hard work!

**Comment by wellyshen** [comment]
@pleerock Not quite sure about the use case of your use case. Maybe you can refer to the [pre-pending items](https://github.com/wellyshen/react-cool-virtual#pre-pending-items) and [sticky to bottom](https://github.com/wellyshen/react-cool-virtual#sticking-to-bottom) examples for the chatroom.

**Comment by pleerock** [comment]
I saw both examples.

It's not clear how to load items in both directions.

For example, in a real chat application you might have 1000 messages. Let's say you show only 10 messages in a time (e.g. BATCH_COMMENTS = 10). But you need to show messages starting from 800, because you have 200 unread messages. But you cannot load 200 messages when you enter the room (because of too many messages). So, you load 10 messages from 800 position. Then user can scroll down and load from 810-820. Or scroll up and load 790-800. Loading occurs in both directions. Bi-directional loading and appending / prepending.

**Comment by pleerock** [comment]
Okay, the way I found a solution is something like this:

```ts
 const { outerRef, innerRef, items, scrollToItem } = useVirtual({
    itemCount: messages.length,
    loadMoreCount: 20,
    itemSize: 50, 
    isItemLoaded: (loadIndex) => loadingStatuses.current[loadIndex],
    onScroll: (event) => {
      if (event.visibleStartIndex < 1) {
        console.log("load backward")
      } else if (event.visibleStopIndex === messages.length - 1) {
        console.log("load forward")
      }
    },
  })
```

Please confirm if I did all right.

**Comment by wellyshen** [comment]
@pleerock Yea, the `onScroll` event can help you for that.
