### ISSUE TITLE
`requestAnimationFrame` doesn't really help with scroll jumping

### ISSUE THREAD

**Issue by pleerock** [wellyshen/react-cool-virtual#361]
`requestAnimationFrame` practice in "Pre-pending Items" demo doesn't help a lot with scroll jumping. Yes, maybe it helps "a bit", but the lag is pretty annoying even in provided demo. 

I checked how it works in real app (much more heavy than your demo) and observed lag is pretty much noticeable. 
Any other ways how to prevent this lag?

**Comment by wellyshen** [comment]
@pleerock You can try the following adjust:

```js
const { outerRef, innerRef, items, scrollToItem } = useVirtual({
    itemCount: comments.length,
    // Provide the estimation size of your item
    itemSize: 200,
  });
  
// ...

useEffect(() => {
    // Remove `requestAnimationFrame`
    scrollToItem({ index: BATCH_COMMENTS, align: "start" }, () => {
      if (comments.length < TOTAL_COMMENTS) shouldFetchData = true;
    });
  }, [comments.length, scrollToItem]);
```

**Comment by pleerock** [comment]
From what I can see you removed `requestAnimationFrame` and added `itemSize`. I already had itemSize set to `50` before. However I'm not sure what value to set, because message can either be a single line, either half of the page (e.g. think of github issue comments).

I removed `requestAnimationFrame` but didn't feel the difference - lag still presents.

**Comment by wellyshen** [comment]
@pleerock There's a [PR](https://github.com/wellyshen/react-cool-virtual/pull/368) for this issue, could you mind to help me verify it by your case first?

**Comment by wellyshen** [comment]
@pleerock This issue can be solved through [v0.6.0](https://github.com/wellyshen/react-cool-virtual/releases/tag/v0.6.0)

**Comment by wellyshen** [comment]
@pleerock For this issue, an optimized version will be provided soon.

**Comment by wellyshen** [comment]
@pleerock Try [v0.7.0](https://github.com/wellyshen/react-cool-virtual/releases/tag/v0.7.0)
