### ISSUE TITLE
When chrome smooth scrolling flag is enabled, the scrollToItem api is not working as expected.

### ISSUE THREAD

**Issue by twoKilo** [wellyshen/react-cool-virtual#388]
# Bug Report

## Describe the Bug

When chrome smooth scrolling flag is enabled, the scrollToItem api is not working as expected.

## How to Reproduce

1. chrome://flags/#smooth-scrolling (ONLY: Windows, Linux, Chrome OS, Android)
2. toggle smooth-scrolling into Enabled
3. scrollToItem is not working

## Expected Behavior

scrollToItem is working and the success callback should be invoked.

## Screenshots

Add screenshots to help explain your problem.

## Your Environment

- Device: PC
- OS: Windows
- Browser: Chrome
- Version: 0.5.5

## Additional Information

This bug can only be reproduced on **Windows**. I've already ship this package into production env, please help me with this issue. 
Thanks.

**Comment by wellyshen** [comment]
@twoKilo Can you show me the reproduced video?

**Comment by twoKilo** [comment]
> @twoKilo Can you show me the reproduced video? BTW, if you set the `smooth` of the `scrollToItem` to `false`. Does it work as expected?

After setting option smooth into false, it is still not working.


[here is the reproduced video]( https://drive.google.com/file/d/1QUkbJK9PULMwm8ciLra6HB-L2JVbRV8i/view?usp=sharing)

you can see that it's not scrolled to the latest message and can only scroll the list by dragging the scrollbar.


[here is the normal behavior](https://drive.google.com/file/d/19GMZmvVX5zHvrFKFzFw_wd3lAOuoCImb/view?usp=sharing)

_ps: can we speak Chinese,pls?_

**Comment by wellyshen** [comment]
@twoKilo 

Sorry I don't have Windows OS in my Macbook Pro, so I need your help for debugging. Is there any error on the console tab of your Google Dev Tools?

You can delete the GIFs.

I think we'd better use English for the issue because this issue might help other people someday.

**Comment by twoKilo** [comment]
@wellyshen  

No, there is no error either on the console or Dev tool. I will test the functionality of `scrollTo` later, but I can't use `startItem` cause I am using version 0.5.5, and upgrading a package in my company takes some efforts... But do let me know if you want it to be verified.

Also, I've received a feedback from test team that the auto scroll feature is not working on **Sogou**  browser(speed version) which is achieved by using `scrollToItem` api. And I've tried the `scrollTo`, it's working as expected on Sogou browser.

Currently I am also on MacOS, I'll get back to you with a reproducing demo on Sogou browser as soon as I can.

**Comment by wellyshen** [comment]
@twoKilo Can you upgrade to the latest version then test these methods locally? I think we can focus on Google Chrome first because Sogou is based on Chromium.

**Comment by twoKilo** [comment]
@wellyshen I've upgraded to the 0.6.0 version, and tested on Windows (smooth scroll enabled), and `scrollToItem` is still not working.

I think Sogou does not share the same issue with Chrome on Windows(smooth scroll enabled). But okay, we can focus on the topic issue first. Still I hope you can look into Sogou issue anyway.

Appreciated.

**Comment by wellyshen** [comment]
@twoKilo How about the 'startItem' and 'scrollTo' do them work?

**Comment by twoKilo** [comment]
@wellyshen I've updated to v0.7.0, and  tested on Windows (smooth scroll enabled), `scrollToItem` and `startItem` both not working. `scrollTo` is working as expected.

**Comment by wellyshen** [comment]
@twoKilo Have you enabled the `smooth: true` when using the `scrollToItem` and `scrollTo` methods?

**Comment by wellyshen** [comment]
@twoKilo I have gotten a Windows laptop, will investigate this issue soon.

**Comment by wellyshen** [comment]
@twoKilo Sorry I'm busying recently. Will investigate this issue once I have time.

**Comment by wellyshen** [comment]
@twoKilo Hey mate, sorry for the late response. I tried to reproduce this issue on Windows 11 + Chrome + smooth scrolling enabled, but I can't reproduce it. Did I miss something?

https://user-images.githubusercontent.com/21308003/164986004-cecc1c66-3cb6-4090-b7b8-f9f645621273.mov

**Comment by wellyshen** [comment]
@twoKilo Feel free to re-open it if you still encounter this problem.

**Comment by romadryud** [comment]
@wellyshen Idk if it the same, but I faced issue when `scrollBehavior: "smooth"` set to `outer` and if you have "light" data it will start lagging about on 300th element, but in work i have heavy one and I faced it from start. There [example](https://codesandbox.io/s/rcv-scroll-to-methods-forked-jzjbpf?file=/DynamicSize.js:620-644) forked from RCV examples. Of course there are no issue when we delete `scrollBehavior: "smooth"` from `outer`
