### ISSUE TITLE
OuterRef and InnerRef can`t assign to my elements

### ISSUE THREAD

**Issue by MaksimWeb** [wellyshen/react-cool-virtual#413]
# Bug Report

I use this library in my react project, so when i create a data list like in examples from documentation i get an error.
 
![изображение](https://user-images.githubusercontent.com/73286420/156509621-c85d0476-aabb-4bf0-a8b9-328336a3f6b3.png)

These components are just styled div elements. And i also tried it with casual div-tag.

I don`t know what happens and can`t find solution in the internet.

That`s an exception: 

![изображение](https://user-images.githubusercontent.com/73286420/156510739-84d1e7f6-3286-406a-a1ba-5e20e8bae221.png)

![изображение](https://user-images.githubusercontent.com/73286420/156510788-933008fc-e92b-447b-80ce-f9504acf6eeb.png)

**Comment by wellyshen** [comment]
@MaksimWeb You can assign the element type of your `outerRef` / `innerRef` for the hook.

```js
const props = useVirtual<HTMLDivElement>();
```
