### ISSUE TITLE
Reverse infinity scroll with Safari / iOS flickers and jumps

### ISSUE THREAD

**Issue by agamrp** [wellyshen/react-cool-virtual#415]
# Bug Report

## Describe the Bug

When pre-pending on a reverse list with Safari the list will jump to the top of the added data, sometimes the list will also flicker when new data is added. 

This is reproducible for me on iOS/Safari (iphone and ipad) using the reverse infinite scroll example https://codesandbox.io/s/rcv-prepend-items-ui06h (mentioned in https://github.com/wellyshen/react-cool-virtual/issues/230).

Is there a way to suspend scrolling (or prevent scroll events) when reaching the top of the list before pre-pending more items?

Thanks for this library!

## How to Reproduce

Run the below sandbox on iOS using Safari and scroll up to load new data.

## CodeSandbox Link

https://codesandbox.io/s/rcv-prepend-items-ui06h

## Expected Behavior

Ideally the scroll position would stay at the top of the list like how it works on chrome/desktop currently instead of jumping to the top of the new items added.

## Screenshots

https://user-images.githubusercontent.com/433174/156864889-9a2ec32e-918f-4c81-86a1-c03e77fc2770.mov

## Your Environment

- Device: iPhone, iPad
- OS: iOS
- Browser: Safari
- Version: iOS 16

**Comment by wellyshen** [comment]
@agamrp I throttle the network for demonstration. You can decrease the `setTimeout` duration to see if it meets your need.
