### ISSUE TITLE
sticking to bottom invalid without "smooth"

### ISSUE THREAD

**Issue by qianjiachun** [wellyshen/react-cool-virtual#432]
# Bug Report

## Describe the Bug
In my project, I accept data and render lists through **websocket**. In some cases, I don't want to use smooth, so I found this problem.
The problem occurs in concurrent network requests(maybe, i guess😂). When smooth is set to false, it cannot stick to bottom.  
But when smooth is set to true, the bug disappears

## How to Reproduce

👉[CodeSandbox](https://codesandbox.io/s/rcv-stick-to-bottom-forked-0o040x?file=/index.js).  
Although the code is not well written, it can be reproduced. I modified lines 43 and 53. You can see the effect

## CodeSandbox Link

Show me the bug on [CodeSandbox](https://codesandbox.io/s/rcv-stick-to-bottom-forked-0o040x?file=/index.js).

## Expected Behavior

sticking to bottom all the time

**Comment by qianjiachun** [comment]
I found that even if smooth is set to true, [this example](https://github.com/wellyshen/react-cool-virtual#sticking-to-bottom) will fail when websocket accepts a lot of data at the same time

**Comment by wellyshen** [comment]
@qianjiachun You can solve the issue by calling the `scrollToItem` after the data is fetched.

**Comment by qianjiachun** [comment]
> 

In my project, the data comes from websocket. The specific process is: websocket = > msgList = > render.  
Then I use `useEffect`:
```
useEffect(() => {
        if (shouldSticky) {
          isScrolling = true;
          scrollToItem({ index: msgList.length - 1}, () => {
            isScrolling = false;
        });
      }
}, [danmakuList, shouldSticky, scrollToItem]);
```

This doesn't always stay at the bottom (that is, your scroll wheel can always scroll down a little bit). Is there a problem with the code I wrote?😥

**Comment by wellyshen** [comment]
@qianjiachun You can call `scrollToItem` after the state of the list items is updated. For example, wrap the `scrollToItem` by `setTimeout` is a way.
