### ISSUE TITLE
scrollToItem doesn't work as expected when using StickyHeaders

### ISSUE THREAD

**Issue by ROTGP** [wellyshen/react-cool-virtual#445]
# Bug Report

## Describe the Bug

scrollToItem doesn't work as expected when using StickyHeaders. When scrolling to an index, and align is 'start',  it should be scrolled to the top, but still be visible underneath any 'stuck' headers. Currently, it's scrolled to the absolute top, and thus, is obscured by sticky heads.

## How to Reproduce

Create a a demo with sticky headers and try to scrollToItem to an index which is not a sticky header.

**Comment by wellyshen** [comment]
@ROTGP Thank you, I will investigate it soon.

**Comment by wellyshen** [comment]
@ROTGP Hey mate, I think it's the expected behavior because it's [how a sticky item works](https://developer.mozilla.org/en-US/docs/Web/CSS/position#try_it). If you want an item to be scrolled on the top without be covered by the sticky item, maybe you can try this:

```js
scrollToItem({ index: 10 - 1, align: "start" });
```

**Comment by ROTGP** [comment]
I don't really agree with you. And your approach will not work when scrolling to variable-sized rows/headers,  but thanks for your response.

**Comment by wellyshen** [comment]
@ROTGP For your case, you might can dynamically disable the `position: sticky` CSS property for the sticky item via the callback of [scrollToItem](https://github.com/wellyshen/react-cool-virtual#scrolltoitem)
